// Common BMSCE branches/degrees for the profile dropdown. Sorted alphabetically
// here at the source so both onboarding and profile-edit (which share this
// constant) stay in sync. "Other" is the catch-all and stays pinned last.
const BRANCH_OPTIONS = [
  "Computer Science",
  "Information Science",
  "Electronics & Communication (ECE)",
  "Electrical & Electronics",
  "Electronics & Instrumentation",
  "Mechanical",
  "Civil",
  "Industrial Engineering & Management",
  "Chemical",
  "Biotechnology",
  "Medical Electronics",
  "Telecommunication",
  "Aerospace",
  "Architecture",
];

export const BRANCHES: readonly string[] = [
  ...[...BRANCH_OPTIONS].sort((a, b) =>
    a.localeCompare(b, undefined, { sensitivity: "base" })
  ),
  "Other",
];

export const EXPERIENCE_LEVELS = [
  "Entry-level",
  "1-3 years",
  "3-5 years",
  "5+ years",
] as const;

export const MENTOR_EXPERTISE = [
  "Software Engineering",
  "Product Management",
  "Data & AI/ML",
  "Design / UX",
  "Hardware & Electronics",
  "Civil & Structural",
  "Mechanical & Manufacturing",
  "Entrepreneurship / Startups",
  "Consulting",
  "Finance",
  "Higher Studies / Grad School",
  "Research",
] as const;

// Standard industry list for the Directory (filterable, consistent). Sorted at
// the source; "Other" stays last as the catch-all.
const INDUSTRY_OPTIONS = [
  "Technology",
  "Finance",
  "Healthcare",
  "Consulting",
  "Manufacturing",
  "Education",
  "Government",
  "Design",
  "Media",
  "Legal",
  "Retail",
  "Energy",
  "Real Estate",
  "Nonprofit",
];

export const INDUSTRIES: readonly string[] = [
  ...[...INDUSTRY_OPTIONS].sort((a, b) =>
    a.localeCompare(b, undefined, { sensitivity: "base" })
  ),
  "Other",
];

// Full country list for the profile location fields. Sorted alphabetically at
// the source (India included in its normal alphabetical spot, not pinned).
const COUNTRY_OPTIONS = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Andorra",
  "Angola",
  "Antigua and Barbuda",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Azerbaijan",
  "Bahamas",
  "Bahrain",
  "Bangladesh",
  "Barbados",
  "Belarus",
  "Belgium",
  "Belize",
  "Benin",
  "Bhutan",
  "Bolivia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Brunei",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cabo Verde",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Comoros",
  "Congo (Congo-Brazzaville)",
  "Congo (Democratic Republic)",
  "Costa Rica",
  "Cote d'Ivoire",
  "Croatia",
  "Cuba",
  "Cyprus",
  "Czechia",
  "Denmark",
  "Djibouti",
  "Dominica",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Eritrea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gabon",
  "Gambia",
  "Georgia",
  "Germany",
  "Ghana",
  "Greece",
  "Grenada",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Holy See",
  "Honduras",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Iran",
  "Iraq",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Kuwait",
  "Kyrgyzstan",
  "Laos",
  "Latvia",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Liechtenstein",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Maldives",
  "Mali",
  "Malta",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Micronesia",
  "Moldova",
  "Monaco",
  "Mongolia",
  "Montenegro",
  "Morocco",
  "Mozambique",
  "Myanmar",
  "Namibia",
  "Nauru",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Nicaragua",
  "Niger",
  "Nigeria",
  "North Korea",
  "North Macedonia",
  "Norway",
  "Oman",
  "Pakistan",
  "Palau",
  "Palestine State",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Rwanda",
  "Saint Kitts and Nevis",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Samoa",
  "San Marino",
  "Sao Tome and Principe",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Seychelles",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "Solomon Islands",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Turkmenistan",
  "Tuvalu",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Vanuatu",
  "Venezuela",
  "Vietnam",
  "Yemen",
  "Zambia",
  "Zimbabwe",
];

export const COUNTRIES: readonly string[] = [...COUNTRY_OPTIONS].sort((a, b) =>
  a.localeCompare(b, undefined, { sensitivity: "base" })
);

// India's 28 states + 8 union territories, for the profile location fields.
// Sorted alphabetically at the source.
const INDIA_STATE_OPTIONS = [
  "Andaman and Nicobar Islands",
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chandigarh",
  "Chhattisgarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu and Kashmir",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Ladakh",
  "Lakshadweep",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Puducherry",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
];

export const INDIA_STATES: readonly string[] = [...INDIA_STATE_OPTIONS].sort(
  (a, b) => a.localeCompare(b, undefined, { sensitivity: "base" })
);
